### ISSUE TITLE
"set color of a specific light" does not work

### ISSUE THREAD

**Issue by BooStars** [guddimon-/boblib#5]
Hi guddimon-,
thank you very much for this lib, although i'm very new to python I get it working partially.
When I start the python-enviroment and "import boblib" I'm ready to connect and use i.e.: "bob.setColor(1, 0, 0)" which worked great. All lights red. 
But when I try to set color of a specific light it does not work. For sure I use this command:
"bob.getLight()[11].getColor().setColor(1, 0, 0)" but nothing happens, no response in my python-enviroment and light 12 is still dark.

Any Ideas whats wrong here?
Greetings
BooStar

**Comment by guddimon-** [comment]
Hi BooStars,

I suppose there is missing the part for "sending" to boblight service.

You can achieve this by the following:
    bob,_sendColor()

This may not be optimal, though it does what you need.

Best regards,
guddimon-

**Comment by guddimon-** [comment]
I think I'll add a function for sending the data of a specific light to the service.

The function for setting all lights to a fixed color sends the data automatically. If only one light is changed (by the command you mentioned) it will be necessary to call the new function anyway (but it will send only the light you specify, not all at once which can lead to performance issues - although I did not recognize any)

**Comment by guddimon-** [comment]
Hi BooStars,

I just commited an update for this. Please try it with the following in your code right after you set the color:
´bob.setColor(11)`

This should send the color for light number 12 to the server and the color changes to the value you set before.

If you want to change the color for more than one light, you might use:
´bob.sendColorAll()`

I also added functions for changing speed and interpolation of the lights in the same way:
`bob.sendSpeed(11)`
`bob.sendSpeedAll()`
`bob.sendInterpolation(11)`
`bob.sendInterpolationAll()`

Please let me know if this works or if there is any bug (because this code is untested, sorry for that).

Enjoy it!

Best regards,
guddimon-

**Comment by BooStars** [comment]
Hi guddimon-,
thank you very much but if I get you right, its not working..
I set the color for all Lights with:
`bob.setColor(1, 1, 0) and bob.setPriority(128)`
then I set the color for one light with
`bob.getLight()[11].getColor().setColor(1, 0, 0) and bob.setColor(11)` ?
Anyway.. I get:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: setColor() takes exactly 4 arguments (2 given)`
when i use: `bob.setColor(11)`
when I try to send the color to the light with
`bob.sendColor(11)`
I get:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boblib.py", line 195, in sendColor
    if light < 0 or light >= getlightscount():
NameError: global name 'getlightscount' is not defined
`
Any Ideas?

**Comment by guddimon-** [comment]
Hmm .. this is what I meant with "untested" ;)

`bob.setColor(11)` is just wrong. Sorry, this is my fault. But you got it right with `bob.sendColor(11)`

There is "only" a small bug I made when trying to check if the light is in range.

Please try it again :)

**Comment by BooStars** [comment]
Hi...
no.. there is still something wrong with the getlightscount:
`>>> bob.getLight()[11].getColor().setColor(1, 0, 0)
>>> bob.sendColor(11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boblib.py", line 195, in sendColor
    if light < 0 or light >= self.getlightscount():
AttributeError: Boblight instance has no attribute 'getlightscount'
`

**Comment by guddimon-** [comment]
I now removed the check for "light in range" and add it later when I get my setup back.

Next try please.

**Comment by BooStars** [comment]
Hmm no..
` bob.sendColor(11)
Ping the server
Pong from server: ping 1

Send color of light 11
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boblib.py", line 197, in sendColor
    self._tn.write(self._SETLIGHTRGB.format(_light[light].getName(),
NameError: global name '_light' is not defined
`

**Comment by guddimon-** [comment]
We're getting closer ;)
I hope this one works now...

**Comment by guddimon-** [comment]
arrr .. I just see that I forgot something ...

**Comment by BooStars** [comment]
Yeah.. cool.. thanks a lot....
with this little fix it works fine:
`self._tn.write(self._SETLIGHTRGB.format(_light[light].getName(),`
should be
`self._tn.write(self._SETLIGHTRGB.format(self._light[light].getName(),`
right?

**Comment by guddimon-** [comment]
Yep, this little fix is what I mean :D

**Comment by guddimon-** [comment]
Thank you very much for your assistance with that :)

**Comment by guddimon-** [comment]
fixed by 37698ad5debef5de2ead190ee0d6c286f4e954f7
